spring:
#  main:
#    allow-circular-references: true
  data:
    mongodb:
      uri: mongodb+srv://nthai2001cr:H1q54razaxG0HE1T@cluster0.41zzcbg.mongodb.net/spring-boot-mongodb?retryWrites=true&w=majority
      auto-index-creation: true
  cloud:
    aws:
      credentials:
        access-key: "AKIA33GEEB7PNSI6J6AA"
        secret-key: "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"
      region:
        static: "ap-southeast-1"
server:
  port: 5000
  servlet:
    encoding:
      charset: "UTF-8"
      force: true
jwt:
  settings:
    accessTokenExpiryTimeSeconds: 1800
    refreshTokenExpiryTimeSeconds: 2592000
    tokenSigningKeyString: "vietcaikeyquanquegichodu256bitsbaygioroidmvietnhieuvanchuadulasao"
    tokenIssuer: "localhost"
logging:
  level:
    org:
      springframework:
        security: "TRACE"
        data:
          mongodb:
            core:
              MongoTemplate: "DEBUG"
security:
  oauth2:
    googleClientId: "66028302633-0eoupfkn27i2sm67jl3fucsg799ni25d.apps.googleusercontent.com"
    googleClientSecret: "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"
  passwordPolicy:
    isWhitespacesAllowed: false
    repeatedPasswordAllowed: false
    minimumLength: 6
    minimumLowerCharacters: 0
    minimumUpperCharacters: 1
    minimumSpecialCharacters: 0
    passwordReuseFrequencyDays: 0
  maxFailedLoginAttempts: 3
  failedLoginLockExpirationMillis: 5000 # 5 seconds
  activationTokenExpirationMillis: 300000 # 5 minutes
  passwordResetTokenExpirationMillis: 300000 # 5 minutes
  failedLoginIntervalMillis: 10000 # 10 seconds
mailing:
  host: "smtp.gmail.com"
  port: 587
  username: "mochacr0@gmail.com"
  password: "nhxyxrnqckoijmcs"
  timeout: 10000
payment:
  momo:
    partnerCode: "MOMOBKUN20180529"
    accessKey: "klm05TvNBzhg7h7j"
    secretKey: "at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa"
shipping:
  ghtk:
    apiToken: "641cd4f20fecc058dc822b5163ceb3abb797431f"


